export interface Tool {
  id: string
  name: string
  description: string
  category: string
  pricing: string
  url: string
  bestFor: string
  isPremium?: boolean
  roles: string[]
  goals: string[]
  budgets: string[]
  experienceLevels: string[]
  teamSizes: string[]
  useCases: string[]
}

export const toolsData: Tool[] = [
  {
    id: "jasper",
    name: "Jasper",
    description: "AI writing assistant that helps create high-quality content for marketing, blogs, and more.",
    category: "Content Creation",
    pricing: "From $49/month",
    url: "https://www.jasper.ai",
    bestFor: "Marketing teams and content creators",
    roles: ["marketer", "writer", "entrepreneur"],
    goals: ["productivity", "creativity"],
    budgets: ["medium", "high"],
    experienceLevels: ["beginner", "intermediate", "advanced"],
    teamSizes: ["solo", "small", "large"],
    useCases: ["content"],
  },
  {
    id: "copy-ai",
    name: "Copy.ai",
    description: "AI copywriting tool that generates high-quality copy for various marketing needs.",
    category: "Content Creation",
    pricing: "Free plan available, Pro from $36/month",
    url: "https://www.copy.ai",
    bestFor: "Marketers and small businesses",
    roles: ["marketer", "writer", "entrepreneur"],
    goals: ["productivity", "creativity"],
    budgets: ["free", "low", "medium"],
    experienceLevels: ["beginner", "intermediate"],
    teamSizes: ["solo", "small"],
    useCases: ["content"],
  },
  {
    id: "midjourney",
    name: "Midjourney",
    description: "AI art generator that creates stunning images from text descriptions.",
    category: "Image Generation",
    pricing: "From $10/month",
    url: "https://www.midjourney.com",
    bestFor: "Designers and creative professionals",
    roles: ["designer", "marketer"],
    goals: ["creativity"],
    budgets: ["low", "medium"],
    experienceLevels: ["beginner", "intermediate", "advanced"],
    teamSizes: ["solo", "small"],
    useCases: ["images"],
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    description: "AI pair programmer that helps you write code faster with suggestions based on comments and context.",
    category: "Coding",
    pricing: "From $10/month",
    url: "https://github.com/features/copilot",
    bestFor: "Developers of all levels",
    isPremium: true,
    roles: ["developer"],
    goals: ["productivity", "automation"],
    budgets: ["low", "medium"],
    experienceLevels: ["beginner", "intermediate", "advanced"],
    teamSizes: ["solo", "small", "large"],
    useCases: ["coding"],
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    description: "AI writing assistant integrated into Notion that helps with drafting, editing, and summarizing.",
    category: "Productivity",
    pricing: "From $10/month (plus Notion subscription)",
    url: "https://www.notion.so/product/ai",
    bestFor: "Knowledge workers and teams",
    isPremium: true,
    roles: ["writer", "marketer", "entrepreneur", "other"],
    goals: ["productivity", "creativity"],
    budgets: ["low", "medium"],
    experienceLevels: ["beginner", "intermediate"],
    teamSizes: ["solo", "small", "large"],
    useCases: ["content", "research"],
  },
  {
    id: "zapier",
    name: "Zapier",
    description: "Automation platform that connects apps and automates workflows with AI capabilities.",
    category: "Automation",
    pricing: "Free plan available, from $19.99/month",
    url: "https://zapier.com",
    bestFor: "Business automation and integration",
    roles: ["entrepreneur", "marketer", "other"],
    goals: ["automation", "productivity"],
    budgets: ["free", "low", "medium", "high"],
    experienceLevels: ["beginner", "intermediate", "advanced"],
    teamSizes: ["solo", "small", "large"],
    useCases: ["automation"],
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    description: "Conversational AI that can answer questions, generate content, and assist with various tasks.",
    category: "General AI",
    pricing: "Free plan available, Plus from $20/month",
    url: "https://chat.openai.com",
    bestFor: "General purpose AI assistance",
    roles: ["marketer", "writer", "developer", "designer", "entrepreneur", "other"],
    goals: ["productivity", "creativity", "learning"],
    budgets: ["free", "low"],
    experienceLevels: ["beginner", "intermediate", "advanced"],
    teamSizes: ["solo", "small"],
    useCases: ["content", "research", "coding"],
  },
  {
    id: "dalle",
    name: "DALL-E",
    description: "AI system that creates realistic images and art from text descriptions.",
    category: "Image Generation",
    pricing: "Pay-per-use credits",
    url: "https://openai.com/dall-e-3",
    bestFor: "Creating custom visuals from text",
    isPremium: true,
    roles: ["designer", "marketer", "entrepreneur"],
    goals: ["creativity"],
    budgets: ["low", "medium"],
    experienceLevels: ["beginner", "intermediate", "advanced"],
    teamSizes: ["solo", "small"],
    useCases: ["images"],
  },
  {
    id: "grammarly",
    name: "Grammarly",
    description: "AI writing assistant that checks grammar, spelling, and style with advanced suggestions.",
    category: "Writing",
    pricing: "Free plan available, Premium from $12/month",
    url: "https://www.grammarly.com",
    bestFor: "Writers and professionals who write frequently",
    roles: ["writer", "marketer", "entrepreneur", "other"],
    goals: ["productivity"],
    budgets: ["free", "low"],
    experienceLevels: ["beginner", "intermediate", "advanced"],
    teamSizes: ["solo", "small", "large"],
    useCases: ["content"],
  },
  {
    id: "descript",
    name: "Descript",
    description: "All-in-one audio/video editing with AI transcription, voice cloning, and editing tools.",
    category: "Media Editing",
    pricing: "Free plan available, from $12/month",
    url: "https://www.descript.com",
    bestFor: "Podcasters and video creators",
    isPremium: true,
    roles: ["marketer", "entrepreneur"],
    goals: ["productivity", "creativity"],
    budgets: ["free", "low", "medium"],
    experienceLevels: ["beginner", "intermediate"],
    teamSizes: ["solo", "small"],
    useCases: ["content"],
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    description: "AI research assistant that provides accurate answers with cited sources.",
    category: "Research",
    pricing: "Free plan available, Pro from $20/month",
    url: "https://www.perplexity.ai",
    bestFor: "Research and information gathering",
    isPremium: true,
    roles: ["writer", "marketer", "developer", "entrepreneur", "other"],
    goals: ["learning", "research", "analysis"],
    budgets: ["free", "low"],
    experienceLevels: ["beginner", "intermediate", "advanced"],
    teamSizes: ["solo", "small"],
    useCases: ["research"],
  },
  {
    id: "anthropic-claude",
    name: "Claude",
    description: "Conversational AI assistant with strong reasoning and long context capabilities.",
    category: "General AI",
    pricing: "Free plan available, Pro from $20/month",
    url: "https://claude.ai",
    bestFor: "Complex reasoning and long documents",
    isPremium: true,
    roles: ["writer", "developer", "entrepreneur", "other"],
    goals: ["productivity", "learning", "analysis"],
    budgets: ["free", "low"],
    experienceLevels: ["intermediate", "advanced"],
    teamSizes: ["solo", "small"],
    useCases: ["content", "research"],
  },
]
